## NumpPy

NumPy is a foundational open source python library for scientific computing. 
It provides high performance, multidimensional array objects and massive collection of tools for working with them. 
Like:
- Linear Algebra
- Fourier Transforms
- Statistics

Pandas, Matplotlib, Scikit-learn, TensorFLow/PyTorch are built on the top of the Numpy.


In [68]:
# import numpy library for numerical operations. we can use it to create arrays, perform mathematical operations, and more.
import numpy as np

In [69]:
np.__version__

'2.4.4'

## Creating NumPy Array

NumPy Array is also know as ndarray.
It is a powerful N-Dimensional gride of values used for numerical and scientific computing in python.
It has characteristics: Homogeneity, Fixed Size, Performance, etc.
NumPy Array Attributes:
 - ndim --> The number of dimensions in rank.
 - shape --> A tuple representing the size of each dimension (Rows & Columns)
 - size --> The total number of elements in the Array.
 - dtype --> The data types of elements (int64, float32)

In [70]:
list1 = [1, 2, 3, 4, 5]
print(list1)

[1, 2, 3, 4, 5]


In [71]:
# we can convert a list to a numpy array using the np.array() function. 
# This allows us to perform various operations on the array efficiently.

array1 = np.array(list1)
print(type(array1))
print(len(array1))
print(array1)

<class 'numpy.ndarray'>
5
[1 2 3 4 5]


In [72]:
# shape of the array use to total number of rows and columns in the array
array1.shape

(5,)

In [73]:
# ndim is use to find the number of dimensions in the array
array1.ndim

1

In [74]:
# we can also create a 2D array (matrix) using a list of lists. Each inner list represents a row in the matrix.
list2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]

]
print(list2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [75]:
# we can convert the list of lists to a 2D numpy array using the np.array() function. 
# This will create a 2D array (matrix) where each inner list becomes a row in the matrix.
array2 = np.array(list2)
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [76]:
# shape of the 2D array will give us the number of rows and columns in the matrix. 
# In this case, it will return (2, 4) which means there are 2 rows and 4 columns in the array.
array2.shape

(2, 4)

In [77]:
# ndim is used to find the number of dimensions in the array
array2.ndim

2

## Numpy array methods:
first import numpy as np
 - np.array() --> converts a list or tuple into an array
 - np.zeros() --> creates an array filled with zeros
 - np.ones() --> create an array filled with ones
 - np.arange() --> crate an array with a range of values 
 - np.linspace() --> evenly spaced numbers over an interval
 - array(): Creates NumPy arrays from Python lists
 - full(): Creates an array with all elements initialized to same user-specified value
 - diag(): Creates NumPy array with the provided list of numbers as the diagonal elements and zeros elsewhere
 - eye(): Creates NumPy array with ones on the diagonal and zeros elsewhere
 - identity(): Creates an identity matrix
 - random.rand(): Creates NumPy array of random numbers sampled from a uniform distribution


In [78]:
# we can also create arrays filled with zeros using the np.zeros() function. 
# This function takes the shape of the array as an argument and returns an array filled with zeros
np.zeros(shape=(2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [79]:
# we can create a 3D array (tensor) using a list of lists of lists. 
# Each inner list represents a 2D array (matrix) in the tensor.
np.zeros(shape=(3,4,4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [80]:
# we can also create arrays filled with a specific value using the np.full() function.
np.full(shape=(4,5), fill_value=2_00)

array([[200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200]])

In [81]:
# arrange is use to create a sequence of numbers in the array (start, stop, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [82]:
# we can also create an array of random numbers using the np.random.rand() function.
import random
random.randint(1,50)

19

In [83]:
# we can also create an array of random integers using the np.random.randint() function.
# It is use to generate random integeers between a specified range (low, high) in array format.

np.random.randint(1, 50)

37

In [84]:
# we can also create a 2D array of random integers using the np.random.randint() function by specifying the size of the array.
np.random.randint(1,50, size =(2,3))

array([[ 6, 34,  2],
       [25, 49, 48]], dtype=int32)

## Accessing an Array
Indexing and Slicing NumPy Arrays
NumPy arrays can be indexed and sliced in several ways depending on the number of dimensions.

Indexing:

Indexing follows a simple rule that we may have encountered before. Let's give it a try.
- 1D Array: array_name[idx] (Similar to Python list)
- 2D Array: array_name[row_idx, col_idx] (Similar to Matrix)
- ND Array: array_name[dim1_idx, dim2_idx, ..., dimN_idx]

OR

- 2D Array: array_name[row_idx][col_idx]
- ND Array: array_name[dim1_idx][dim2_idx] ... [dimN_idx]

Slicing:
Slicing follows the same rule as indexing. The only difference is that for each dimension we provide it with a range of indeces and sometimes (optional) step size (similar to arange() function discussed above).

- 1D Array: array_name[idx1:idx2:step]
- 2D Array: array_name[row_idx1:row_idx2:step1, col_idx1:col_idx2:step2]
- ND Array: array_name[dim1_idx1:dim1_idx2:step1, ..., dimN_idx1:dimN_idx2:stepN]

In [85]:
# 1D array
a = np.array([1,2,3,4,5])

In [86]:
# we can access elements in the array using indexing.
a[-3]

np.int64(3)

In [87]:
# we can also access a range of elements in the array using slicing.
# slicing syntax is [start:stop:step]. If we omit start, it defaults to the beginning of the array. If we omit stop, it defaults to the end of the array. If we omit step, it defaults to 1.
a[:3:]

array([1, 2, 3])

In [88]:
# 2D array
b = np.random.randint(0, 20, size=(3, 4))
b

array([[ 5, 16, 14, 14],
       [11, 18, 16,  9],
       [ 8, 13, 13,  7]], dtype=int32)

In [89]:
# we can access elements in a 2D array using row and column indices. 
# The syntax is array[row_index, column_index].
b[1,0]

np.int32(11)

In [ ]:
# we can also access the last element in the array using negative indexing.
b[-1, -1]

np.int32(7)

In [ ]:
# we can also access elements in the array using negative indexing.
b[-3]

array([ 5, 16, 14, 14], dtype=int32)

In [ ]:
# Slicing 2D Array
# Syntax: array[row_start:row_stop:row_step, column_start:column_stop:column_step]
b[0::2, 2::]

array([[14, 14],
       [13,  7]], dtype=int32)

In [ ]:
# Syntax: array[row_start:row_stop:row_step, column_start:column_stop:column_step]
b[:2, 1]

array([16, 18], dtype=int32)

In [ ]:
# 3D array (tensor)
# syntax: np.random.randint(low, high, size=(block of array, rows, columns))
c = np.random.randint(0, 20, size=(3, 3, 4))
c

array([[[18, 12,  6,  7],
        [ 4, 14,  0,  1],
        [ 0,  6, 19,  0]],

       [[14,  8,  1, 16],
        [17, 18, 15,  7],
        [ 6,  4,  5,  9]],

       [[10, 14, 17, 11],
        [16, 13,  2,  9],
        [14, 14, 16, 14]]], dtype=int32)

In [ ]:
# we can access elements in a 3D array using three indices: block index, row index, and column index.
c[0,1,2]

np.int32(0)

In [ ]:
# 20 colorful images
# Syntax: np.random.randint(low, high, size=(number of images, color channels, height, width))
d = np.random.randint(0, 20, size=(20, 3, 10, 10))
d

array([[[[13, 15, 17, ..., 18, 13,  5],
         [10, 17, 12, ..., 11, 14, 11],
         [ 6, 10, 17, ...,  1, 12, 17],
         ...,
         [12,  8,  9, ..., 11,  4, 15],
         [ 6,  7,  9, ..., 18,  0,  4],
         [14,  8,  2, ..., 19,  5,  9]],

        [[ 8, 10,  5, ...,  2,  3,  7],
         [10,  6,  9, ...,  1, 11, 14],
         [ 3, 17,  3, ..., 11, 13, 15],
         ...,
         [17,  6, 13, ..., 16, 15,  9],
         [19,  9, 10, ...,  0,  6, 15],
         [12,  1,  9, ..., 14, 12, 15]],

        [[13,  8,  4, ...,  9,  9,  4],
         [ 0,  6,  6, ...,  7,  9,  7],
         [ 7,  0,  6, ...,  5, 16,  0],
         ...,
         [ 4,  1,  0, ..., 11, 15, 10],
         [18,  2, 16, ..., 12,  5,  6],
         [ 1,  7,  9, ...,  5,  4,  0]]],


       [[[ 8,  0, 14, ...,  3, 12, 19],
         [ 1, 16,  5, ..., 19,  8,  2],
         [ 1, 18,  7, ...,  2, 19, 19],
         ...,
         [ 3,  3,  8, ..., 17,  4,  8],
         [16, 16, 16, ...,  7, 10,  6],
         [14,  4

In [ ]:
# d[-1] will give us the last image in the array, 
# which is a 3D array of shape (3, 10, 10) representing the color channels and dimensions of the image.
d[-1]

array([[[ 6, 19,  8, 10, 11,  8,  8,  0,  2,  3],
        [13,  1, 15,  8,  5, 15,  0,  5, 13, 17],
        [ 0, 15,  8,  1,  3,  4, 10,  2,  7, 13],
        [ 5, 16,  0, 12,  6, 12, 12,  1,  3,  5],
        [18,  6,  5,  5, 14,  0,  5, 13,  6,  6],
        [ 0, 17, 16,  5, 16, 11,  0, 18,  5, 11],
        [17,  9, 13,  3,  6, 10, 12,  9,  9,  1],
        [12,  4,  1,  3, 14, 11,  1,  1, 12, 17],
        [ 7, 19, 15, 16, 15,  9, 15, 15, 16,  7],
        [ 7, 17,  2, 19, 12,  4, 17, 13,  9, 16]],

       [[14, 14,  6, 13, 16,  2, 16,  8,  8, 17],
        [10,  5, 16,  4,  6, 15,  9, 11, 14, 18],
        [18,  0,  0, 19, 10, 16,  6,  9,  7, 11],
        [ 5, 18, 19, 17, 19, 10, 19,  7, 11, 14],
        [18, 14, 10,  9,  4, 15, 10, 16,  4, 16],
        [ 4,  4, 12, 15,  8,  8,  0,  7,  7,  0],
        [ 0,  8,  6,  0,  8,  7, 15, 10,  1, 13],
        [ 5, 19, 17, 10, 18,  7,  2,  6, 10, 19],
        [ 7,  8, 12,  1, 13, 12, 18,  0, 16,  3],
        [ 5,  6, 12, 14, 16, 16, 10, 18, 12,  8]

In [99]:
c.shape

(3, 3, 4)