In [5]:
import numpy as np

In [6]:
np.__version__

'2.4.4'

## Creating NumPy Array

In [9]:
list1 = [1, 2, 3, 4, 5]
print(list1)

[1, 2, 3, 4, 5]


In [11]:
array1 = np.array(list1)
print(type(array1))
print(len(array1))
print(array1)

<class 'numpy.ndarray'>
5
[1 2 3 4 5]


In [12]:
array1.shape

(5,)

In [13]:
array1.ndim

1

In [14]:
list2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]

]
print(list2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [17]:
array2 = np.array(list2)
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [18]:
array2.shape

(2, 4)

In [19]:
array2.ndim

2

## Numpy array methods:

In [21]:
np.zeros(shape=(2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [22]:
np.zeros(shape=(3,10,10), dtype=int)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [24]:
np.full(shape=(4,5), fill_value=2_00)

array([[200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200]])