In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

## Creating NumPy Array

In [3]:
list1 = [1, 2, 3, 4, 5]
print(list1)

[1, 2, 3, 4, 5]


In [4]:
array1 = np.array(list1)
print(type(array1))
print(len(array1))
print(array1)

<class 'numpy.ndarray'>
5
[1 2 3 4 5]


In [5]:
array1.shape

(5,)

In [6]:
array1.ndim

1

In [7]:
list2 = [
    [1, 2, 3, 4],
    [5, 6, 7, 8]

]
print(list2)

[[1, 2, 3, 4], [5, 6, 7, 8]]


In [8]:
array2 = np.array(list2)
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [9]:
array2.shape

(2, 4)

In [10]:
array2.ndim

2

## Numpy array methods:

In [11]:
np.zeros(shape=(2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [12]:
np.zeros(shape=(3,10,10), dtype=int)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [13]:
np.full(shape=(4,5), fill_value=2_00)

array([[200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200],
       [200, 200, 200, 200, 200]])

In [17]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [18]:
import random
random.randint(1,50)

44

In [20]:
np.random.randint(1, 50)

38

In [21]:
np.random.randint(1,50, size =(2,3))

array([[28,  7, 11],
       [14, 29, 43]], dtype=int32)

In [ ]:
#1D
a = np.array([1,2,3,4,5])

In [23]:
a[-3]

np.int64(3)

In [24]:
a[:3:]

array([1, 2, 3])

In [26]:
# 2D
b = np.random.randint(0, 20, size=(5, 4))
b

array([[ 9, 10,  2,  3],
       [10, 13,  4,  4],
       [13,  5, 14, 19],
       [ 6,  3, 19,  1],
       [15, 14,  2, 12]], dtype=int32)

In [27]:
b[1,0]

np.int32(10)

In [28]:
b[-1, -1]

np.int32(12)

In [29]:
b[-3]

array([13,  5, 14, 19], dtype=int32)

In [31]:
# Slicing 2D Array
b[0::2, 2::]

array([[ 2,  3],
       [14, 19],
       [ 2, 12]], dtype=int32)

In [32]:
b[:2, 1]

array([10, 13], dtype=int32)

In [35]:
# 3D 
c = np.random.randint(0, 20, size=(3, 3, 4))
c

array([[[18, 16,  4, 19],
        [11, 10, 15,  1],
        [17,  1,  2, 13]],

       [[16, 12, 16,  5],
        [15,  4,  7,  1],
        [13,  2,  0,  1]],

       [[18, 19, 17,  1],
        [ 1,  3, 19,  0],
        [ 0,  2,  8,  2]]], dtype=int32)

In [39]:
c[0,1,2]

np.int32(15)

In [40]:
# 20 colorful images
d = np.random.randint(0, 20, size=(20,3, 10, 10))
d

array([[[[ 6, 15, 12, ..., 10, 15, 12],
         [10,  5, 12, ..., 19,  5, 12],
         [ 8, 10, 14, ...,  2, 14, 17],
         ...,
         [11,  2, 14, ...,  2,  8, 13],
         [16, 12,  9, ...,  9, 19,  3],
         [17, 18,  2, ..., 16, 13,  4]],

        [[ 7, 16, 14, ..., 14, 14, 10],
         [ 8, 10,  5, ..., 16, 19,  5],
         [16, 14, 12, ...,  7, 16,  0],
         ...,
         [13, 12, 13, ..., 19, 11, 10],
         [19,  0,  2, ...,  1,  1, 15],
         [10,  8, 15, ..., 12,  7, 14]],

        [[15, 11, 16, ..., 16,  8, 13],
         [ 0, 14, 15, ...,  1,  3,  2],
         [ 8, 13, 13, ...,  2, 17, 14],
         ...,
         [19, 14,  6, ..., 18, 14, 16],
         [ 3,  6, 19, ..., 19, 13, 16],
         [ 4, 14,  3, ...,  7,  5,  4]]],


       [[[ 9,  5,  6, ...,  7,  5,  3],
         [ 8,  4,  3, ..., 10,  8, 16],
         [ 9, 18,  9, ...,  5,  5,  9],
         ...,
         [ 2, 15, 14, ..., 19, 11,  1],
         [18, 17, 16, ...,  9, 17,  6],
         [19,  0

In [41]:
d[-1]

array([[[ 5, 10, 11, 13,  9,  6,  4,  7, 17,  7],
        [ 7,  3,  8,  8,  7, 19, 18,  2,  5, 18],
        [ 7, 15,  1, 15, 18, 11, 17, 14,  7, 13],
        [ 4,  4,  7, 19,  3,  0,  3, 13,  7, 12],
        [13, 17, 17, 12, 16, 14,  5,  8,  3,  9],
        [ 9,  7,  0, 13, 16,  5,  0,  0,  6, 12],
        [19, 10, 12, 14,  4,  0, 15,  0,  0, 18],
        [ 4,  0,  0,  9,  3,  8,  5, 10, 11,  5],
        [ 0, 10,  4,  9,  4, 19, 15, 14,  7, 13],
        [13,  8, 11, 13,  7, 17, 16, 17, 15,  0]],

       [[ 1, 11, 17,  2, 10,  6, 14, 17, 10, 13],
        [16,  1, 15,  8, 17, 19, 11,  2, 17,  2],
        [19,  0,  3, 13, 12, 18,  1,  7,  3, 15],
        [ 7, 10,  1, 14, 14,  4, 13,  3, 14,  4],
        [ 2, 12,  3,  5, 15,  1, 14,  0, 17, 17],
        [15, 10, 19, 13,  2, 11,  6, 13, 17,  3],
        [15, 12,  4, 15,  6, 16,  0, 18,  0,  2],
        [16,  6,  6, 15, 10, 19,  6,  2, 15,  4],
        [ 9,  3, 19,  8,  2, 15, 16, 11,  9, 15],
        [ 0,  9, 11, 13,  4, 18, 16,  3,  8,  7]