In [26]:
import numpy as np

In [27]:
arr = np.random.rand(10,50)

In [28]:
arr.shape

(10, 50)

In [29]:
arr.ndim

2

In [30]:
arr.dtype

dtype('float64')

In [31]:
arr.size

500

In [32]:
# Transpose of an array
arr_T = arr.T
arr_T.shape

(50, 10)

In [33]:
arr = np.random.randint(2,5, (3,4))
arr

array([[2, 3, 2, 2],
       [2, 4, 2, 4],
       [4, 3, 2, 2]], dtype=int32)

In [34]:
arr.reshape(2,3, -1)

array([[[2, 3],
        [2, 2],
        [2, 4]],

       [[2, 4],
        [4, 3],
        [2, 2]]], dtype=int32)

In [35]:
flat_arry = arr.flatten()
flat_arry

array([2, 3, 2, 2, 2, 4, 2, 4, 4, 3, 2, 2], dtype=int32)

In [36]:
# arr.sum(axis=0) # column wise sum
# arr.sum(axis=1) # row wise sum
arr.sum() # total sum of all elements in the array

np.int64(32)

In [37]:
arr.prod(axis = 1) # row wise product of all elements in the array

array([24, 64, 48])

In [38]:
arr.cumsum(axis =0) # cumulative sum along the column

array([[ 2,  3,  2,  2],
       [ 4,  7,  4,  6],
       [ 8, 10,  6,  8]])

In [39]:
arr.max()

np.int32(4)

In [40]:
arr.min(axis=0) # column wise minimum

array([2, 3, 2, 2], dtype=int32)

In [41]:
arr.argmax(axis=0) # column wise index of maximum value

array([2, 1, 0, 1])

In [43]:
arr1 = np.random.randint(1,100, (3,4))
arr2 = np.random.randint(1,100, (3,4))

In [44]:
arr1

array([[11, 84, 34, 89],
       [36, 17, 37, 63],
       [24, 33, 12, 60]], dtype=int32)

In [45]:
merged = np.concatenate((arr1, arr2), axis = 0) # row wise merging of two arrays
merged

array([[11, 84, 34, 89],
       [36, 17, 37, 63],
       [24, 33, 12, 60],
       [81, 84, 77,  8],
       [12, 74, 47, 75],
       [79, 74, 86, 12]], dtype=int32)