## ✅ NumPy Operations
# Arithmetic Operations
 - Addition (+)
 - Subtraction (-)
 - Multiplication (*)
 - Division (/)
# Mathematical Functions
 - np.sqrt()
 - np.power()
 - np.exp()
 - np.log()
# Statistical Operations
 - sum()
 - mean()
 - std()
 - min(), max()
# Comparison Operations
 - >, <, ==, !=
# Logical Operations
 - np.logical_and()
 - np.logical_or()
 - np.logical_not()
# Array Manipulation
 - reshape()
 - flatten()
 - transpose() / .T
# Indexing and Slicing
 - Access elements (arr[i])
 - Slice arrays (arr[start:end])
# Broadcasting
 - Operations between arrays of different shapes
# Aggregation Operations
 - argmax(), argmin()
 - cumsum(), cumprod()
# Sorting and Searching
 - np.sort()
 - np.where()
 - np.unique()

In [93]:
import numpy as np

In [94]:
a = np.random.randint(1,6, (2,3))
b = np.random.randint(6,10, (3,3))
c = np.random.randint(1,9, (3,3))
a, b, c

(array([[1, 4, 1],
        [1, 3, 4]], dtype=int32),
 array([[8, 8, 7],
        [6, 9, 8],
        [6, 7, 8]], dtype=int32),
 array([[5, 5, 5],
        [8, 7, 8],
        [5, 4, 7]], dtype=int32))

# 1. Element Opeations

# Arithmetic Operations

In [95]:
# b + c
np.add(b,c) # element wise addition of two arrays

array([[13, 13, 12],
       [14, 16, 16],
       [11, 11, 15]], dtype=int32)

In [96]:
# b - c
np.subtract(b,c) # element wise subtraction of two arrays

array([[ 3,  3,  2],
       [-2,  2,  0],
       [ 1,  3,  1]], dtype=int32)

In [97]:
# b * c
np.multiply(b,c) # element wise multiplication of two arrays

array([[40, 40, 35],
       [48, 63, 64],
       [30, 28, 56]], dtype=int32)

In [98]:
# b / c
np.round(np.divide(b,c), 2) # element wise division of two arrays

array([[1.6 , 1.6 , 1.4 ],
       [0.75, 1.29, 1.  ],
       [1.2 , 1.75, 1.14]])

In [99]:
# modulo
np.mod(b,c) # element wise modulo of two arrays
# b % c

array([[3, 3, 2],
       [6, 2, 0],
       [1, 3, 1]], dtype=int32)

In [114]:
# a ** 2 # element wise exponentiation of an array with a scalar value
np.pow(a, 2) # element wise exponentiation of an array with a scalar value
# np.pow(b,c) # element wise exponentiation of two arrays

array([[  16, 1369,  576],
       [1681,  400,  289]], dtype=int32)

# Trignometric

In [101]:
np.sin(a)

array([[ 0.84147098, -0.7568025 ,  0.84147098],
       [ 0.84147098,  0.14112001, -0.7568025 ]])

In [102]:
cot = 1/np.tan(a)
cot

array([[ 0.64209262,  0.86369115,  0.64209262],
       [ 0.64209262, -7.01525255,  0.86369115]])

# Rounding Operations

In [103]:
np.around(cot, 2)


array([[ 0.64,  0.86,  0.64],
       [ 0.64, -7.02,  0.86]])

In [104]:
np.floor(cot)

array([[ 0.,  0.,  0.],
       [ 0., -8.,  0.]])

In [105]:

np.ceil(cot)

array([[ 1.,  1.,  1.],
       [ 1., -7.,  1.]])

# Matrix Operations

In [106]:
a = np.random.randint(1,50, (2,3))
b = np.random.randint(6,100, (3,3))

In [107]:
a.shape

(2, 3)

In [108]:
b.shape

(3, 3)

In [109]:
# a @ b # matrix multiplication of two arrays
# np.dot(a,b) # matrix multiplication of two arrays
res = a.dot(b) # matrix multiplication of two arrays
res

array([[4209, 2362, 3699],
       [4242, 3901, 2836]], dtype=int32)

In [110]:
res.shape

(2, 3)

In [111]:
# Inverse Matrix
det = np.linalg.det(b) # determinant of a matrix
det


np.float64(-100103.0)

In [112]:
np.linalg.inv(b) # inverse of a matrix

array([[ 0.01925017,  0.04639222, -0.02217716],
       [ 0.00880094, -0.02653267,  0.0100996 ],
       [-0.02644276, -0.02584338,  0.02527397]])