In [100]:
import numpy as np

In [101]:
a = np.random.randint(1,6, (2,3))
b = np.random.randint(6,10, (3,3))
c = np.random.randint(1,9, (3,3))

# 1. Element Opeations

# Arithmetic Operations

In [102]:
# b + c
np.add(b,c) # element wise addition of two arrays

array([[12, 13, 14],
       [10,  9, 14],
       [12, 16, 13]], dtype=int32)

In [103]:
# b - c
np.subtract(b,c) # element wise subtraction of two arrays

array([[ 2, -1, -2],
       [ 4,  5,  2],
       [ 4,  2,  3]], dtype=int32)

In [104]:
# b * c
np.multiply(b,c) # element wise multiplication of two arrays

array([[35, 42, 48],
       [21, 14, 48],
       [32, 63, 40]], dtype=int32)

In [105]:
# b / c
np.divide(b,c) # element wise division of two arrays

array([[1.4       , 0.85714286, 0.75      ],
       [2.33333333, 3.5       , 1.33333333],
       [2.        , 1.28571429, 1.6       ]])

In [106]:
# modulo
# np.mod(b,c) # element wise modulo of two arrays
b % c

array([[2, 6, 6],
       [1, 1, 2],
       [0, 2, 3]], dtype=int32)

In [107]:
# a ** 2 # element wise exponentiation of an array with a scalar value
# np.pow(a, 2) # element wise exponentiation of an array with a scalar value
np.pow(b,c) # element wise exponentiation of two arrays

array([[  16807,  279936, 1679616],
       [    343,      49,  262144],
       [   4096, 4782969,   32768]], dtype=int32)

# Trignometric

In [108]:
np.sin(a)

array([[ 0.84147098, -0.95892427,  0.90929743],
       [ 0.84147098, -0.7568025 , -0.95892427]])

In [109]:
cot = 1/np.tan(a)
cot

array([[ 0.64209262, -0.29581292, -0.45765755],
       [ 0.64209262,  0.86369115, -0.29581292]])

# Rounding Operations

In [110]:
np.around(cot, 2)


array([[ 0.64, -0.3 , -0.46],
       [ 0.64,  0.86, -0.3 ]])

In [111]:
np.floor(cot)

array([[ 0., -1., -1.],
       [ 0.,  0., -1.]])

In [112]:

np.ceil(cot)

array([[ 1., -0., -0.],
       [ 1.,  1., -0.]])

# Matrix Operations

In [113]:
a = np.random.randint(1,50, (2,3))
b = np.random.randint(6,100, (3,3))

In [114]:
a.shape

(2, 3)

In [115]:
b.shape

(3, 3)

In [116]:
# a @ b # matrix multiplication of two arrays
# np.dot(a,b) # matrix multiplication of two arrays
res = a.dot(b) # matrix multiplication of two arrays
res

array([[8153, 6786, 6075],
       [4367, 3593, 3427]], dtype=int32)

In [117]:
res.shape

(2, 3)

In [ ]:
# Inverse Matrix
det = np.linalg.det(b) # determinant of a matrix
det


array([[ 0.66646388, -0.13368821, -0.39041825],
       [-0.57961977,  0.1356654 ,  0.33703422],
       [-0.23923954,  0.0313308 ,  0.15406844]])

In [119]:
np.linalg.inv(b) # inverse of a matrix

array([[ 0.66646388, -0.13368821, -0.39041825],
       [-0.57961977,  0.1356654 ,  0.33703422],
       [-0.23923954,  0.0313308 ,  0.15406844]])